INSERT INTO basic_items (category_name, item_name, main_function, item_description)
VALUES
('Campsite', 'Tent', 'Provide Shelter', 'Is a shelter consisting of sheets of fabric or other material attached to a frame of poles. You can find many different tent sizes, those sizes ranging from 1 to 10 Persons. 1P Tent: Usually comfortable for 1 person with gear stored in the vestibule. 2P Tent: A tight fit for 2 with gear stored within the tent. Will fit 2 regular width sleeping pads. 3P Tent: Great for 2 people with interior gear storage space. Will fit two wide sleeping pads. Comfortable for 2 people plus a small child. A very tight fit for 3 average adults. 4P Tent: Great for 2-3 people with interior gear storage space. Tight but possible to fit 3 people and a child. A very tight fit for 4 average adults. 6P Tent: Comfortable for 4 plus gear. Tight for 5 or 6. 8P Tent:Luxurious for 4 plus gear. Comfortable for 6 if some are children. Tight for 7 or 8. 10P Tent: Luxurious for 4 plus gear. Comfortable for 6 plus gear. Tight for 8+ people.'),
('Campsite', 'Sleeping Bag', 'Portiable bedding', 'It is a insulated covering for a person which allows you to have portiable bedding. Sleeping bags can fall into 3 basic categories Summer, three-season, and winter.'),
('Campsite', 'Sleeping Pad', 'Prevent the loss of body heat', 'In a simple for a sleeping pad consists of a foam-like material that is usually half and inch thick.'),
('Campsite', 'Camping Chairs', 'Seating for the campsite', 'It is a type of folding furniture, a light, portable char that fold flat or to a smaller size.'),
('Campsite', 'Camping Pillow', 'Used to sleep on', 'This is a pillow specifically made for camping, and is typically going to be more waterproof, more lightweight, and more compact than a traditional pillow.'),
('Campsite', 'Headlamps or flashlights(extra batteris)', 'Use for portable lighting.', 'This is a portable hand-held electric light.'),
('Campsite', 'Camp table', 'Used to eat meals at a campsite', 'It is a folding table that allows you to eat your meals, to play games on its surface, place drinks as you sit around a campfire or even cook on the tabletop.'),
('Campsite', 'Lantern(and mantels and fuel/batteries if needed)', 'Main light source for outdoors', 'This usually is a light source that is in a protective enclosure. There are 2 types of lanturns one that uses some tpe of fuel and the other that uses batteries.'),
('Tools & Repair Items', 'Multi-tool', 'Can be used for adjustment, cleaning or minor repairs.', 'Multi tool is a compact, portable device that has blades and extensions for many tools (such as knives, screwdrivers, pliers, scissors, openers, and saw blades) which can be folded inot the handle.'),
('Tools & Repair Items', 'Duct Tape', 'For general sealing', 'Duct tape is a durable tape with a sturdy backing that resists water.'),
('Tools & Repair Items', 'PMI Utility Cord', 'Can be used for tent tie-down, clotheslines and securing various items', 'PMI accessory cord are made of durable kernmantle construction and are great for a wide variety of uses. These cords are made witht he ideal combination of strength, flexibility, and durability.'),
('Tools & Repair Items', 'Tent-pole repair sleeve', 'Used to fix a broken tent pole', 'A repair sleeve is a sort tube(slightly larger in diameter) oftern provided with your tent.'),
('Tools & Repair Items', 'Pad/Matress repair kit', 'Used to repair sleeping pads', 'A pad/matress repair kit uses a wet adhesive and fabric patches to make strong and durable repairs possible. Kits usually include 3 Alcohal prep pads, 6 glue Dots and 3 cover patches.'),
('Tools & Repair Items', 'Mallet or hammer', 'This is use for hammering text stakes', 'They are typically lightweight and ade from solid wood, rubber, or leather. Due to their lack of weight, they are not very good at moving objects a great distance. Instead, they are better suited for seating(nudging) objects together.'),
('Tools & Repair Items', 'Saw or Axe', 'These are used for cutting firewood', 'A saw is a tool consisting of a tough blade, wire, or chain with a hard toothed edge. An axe is a tool used for cutting wood, it consists of a heavy metal blad which is sharp a one edge and attached by is other edge to the end of a long handle.'),
('Tools & Repair Items', 'Small broom and dustpan', 'This is used to clean up the campsite', 'It is a cleaning utinsil that is commenly use to sweap up trash and debris off of the ground.');
