INSERT INTO basic_items (category_name, item_name, main_function, item_description)
VALUES
('Campsite', 'Tent', 'Provide Shelter', 'Is a shelter consisting of sheets of fabric or other material attached to a frame of poles. You can find many different tent sizes, those sizes ranging from 1 to 10 Persons. 1P Tent: Usually comfortable for 1 person with gear stored in the vestibule. 2P Tent: A tight fit for 2 with gear stored within the tent. Will fit 2 regular width sleeping pads. 3P Tent: Great for 2 people with interior gear storage space. Will fit two wide sleeping pads. Comfortable for 2 people plus a small child. A very tight fit for 3 average adults. 4P Tent: Great for 2-3 people with interior gear storage space. Tight but possible to fit 3 people and a child. A very tight fit for 4 average adults. 6P Tent: Comfortable for 4 plus gear. Tight for 5 or 6. 8P Tent:Luxurious for 4 plus gear. Comfortable for 6 if some are children. Tight for 7 or 8. 10P Tent: Luxurious for 4 plus gear. Comfortable for 6 plus gear. Tight for 8+ people.'),
('Campsite', 'Sleeping Bag', 'Portiable bedding', 'It is a insulated covering for a person which allows you to have portiable bedding. Sleeping bags can fall into 3 basic categories Summer, three-season, and winter.'),
('Campsite', 'Sleeping Pad', 'Prevent the loss of body heat', 'In a simple for a sleeping pad consists of a foam-like material that is usually half and inch thick.'),
('Campsite', 'Camping Chairs', 'Seating for the campsite', 'It is a type of folding furniture, a light, portable char that fold flat or to a smaller size.'),
('Campsite', 'Camping Pillow', 'Used to sleep on', 'This is a pillow specifically made for camping, and is typically going to be more waterproof, more lightweight, and more compact than a traditional pillow.'),
('Campsite', 'Headlamps or flashlights(extra batteris)', 'Use for portable lighting.', 'This is a portable hand-held electric light.'),
('Campsite', 'Camp table', 'Use it to eat your meals at the campsite', 'It is a folding table that allows you to eat your meals, to play games on its surface, place drinks as you sit around a campfire or even cook on the tabletop.'),
('Campsite', 'Lantern(and mantels and fuel/batteries if needed)', 'Main light source for outdoors', 'This usually is a light source that is in a protective enclosure. There are 2 types of lanturns one that uses some tpe of fuel and the other that uses batteries.');

